create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.movements (
  id text primary key,
  codigo text not null,
  descripcion text not null,
  cantidad numeric not null check (cantidad > 0),
  valor numeric not null default 0,
  fecha date not null,
  responsable text not null,
  area text not null,
  categoria text,
  tipo text not null check (tipo in ('Entrada', 'Salida')),
  imagen text,
  motivo text,
  created_at timestamptz not null default now()
);

create index if not exists movements_codigo_idx on public.movements (upper(trim(codigo)));
create index if not exists movements_fecha_idx on public.movements (fecha);

alter table public.categories enable row level security;
alter table public.movements enable row level security;

drop policy if exists "categories_public_access" on public.categories;
create policy "categories_public_access"
  on public.categories for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "movements_public_access" on public.movements;
create policy "movements_public_access"
  on public.movements for all
  to authenticated
  using (true)
  with check (true);

insert into public.categories (name)
values
  ('Atención y servicio'),
  ('Empaques y descartables'),
  ('Mantenimiento'),
  ('Tecnología y equipos'),
  ('Seguridad')
on conflict (name) do nothing;