create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.movements (
  id text primary key,
  codigo text not null,
  descripcion text not null,
  cantidad numeric not null check (cantidad > 0),
  unidad_medida text,
  costo numeric not null default 0,
  precio_venta numeric not null default 0,
  valor numeric not null default 0,
  fecha date not null,
  responsable text not null,
  area text not null,
  categoria text,
  tipo text not null check (tipo in ('Entrada', 'Salida')),
  imagen text,
  motivo text,
  created_at timestamptz not null default now()
);

create index if not exists movements_codigo_idx on public.movements (upper(trim(codigo)));
create index if not exists movements_fecha_idx on public.movements (fecha);

alter table public.categories enable row level security;
alter table public.movements enable row level security;

drop policy if exists "categories_public_access" on public.categories;
create policy "categories_public_access"
  on public.categories for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "movements_public_access" on public.movements;
create policy "movements_public_access"
  on public.movements for all
  to authenticated
  using (true)
  with check (true);

insert into public.categories (name)
values
  ('Atención y servicio'),
  ('Empaques y descartables'),
  ('Mantenimiento'),
  ('Tecnología y equipos'),
  ('Seguridad')
on conflict (name) do nothing;

-- ------------------------------------------------------------------
-- Almacenamiento de imágenes de producto (Supabase Storage)
-- ------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do nothing;

drop policy if exists "productos_public_read" on storage.objects;
create policy "productos_public_read"
  on storage.objects for select
  using (bucket_id = 'productos');

drop policy if exists "productos_auth_insert" on storage.objects;
create policy "productos_auth_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'productos');

drop policy if exists "productos_auth_update" on storage.objects;
create policy "productos_auth_update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'productos');

drop policy if exists "productos_auth_delete" on storage.objects;
create policy "productos_auth_delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'productos');
