create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  almacen text not null default 'las-flores',
  created_at timestamptz not null default now(),
  unique (almacen, name)
);

create table if not exists public.movements (
  id text primary key,
  codigo text not null,
  descripcion text not null,
  cantidad numeric not null check (cantidad > 0),
  unidad_medida text,
  costo numeric not null default 0,
  stock_minimo numeric not null default 0,
  valor numeric not null default 0,
  fecha date not null,
  responsable text not null,
  area text not null,
  categoria text,
  tipo text not null check (tipo in ('Entrada', 'Salida')),
  imagen text,
  motivo text,
  almacen text not null default 'las-flores',
  created_at timestamptz not null default now()
);

create index if not exists movements_codigo_idx on public.movements (upper(trim(codigo)));
create index if not exists movements_fecha_idx on public.movements (fecha);
create index if not exists movements_almacen_idx on public.movements (almacen);

-- Catálogo de productos único y compartido entre almacenes: la identidad
-- del producto (descripción, unidad, categoría, imagen) es una sola tabla
-- para todos los almacenes. El stock/costo/stock mínimo sigue siendo 100%
-- de cada almacén — eso vive en movements, no acá. La identidad es `id`
-- (interno, invisible para el usuario) — el código que cada almacén ve,
-- imprime y busca es independiente por almacén, ver `producto_codigos`
-- abajo (antes `codigo` vivía acá mismo como PK y era compartido entre
-- los dos almacenes, lo que obligaba a una numeración global; ver
-- migration-fase17.sql).
create table if not exists public.productos (
  id                uuid primary key default gen_random_uuid(),
  descripcion       text not null,
  unidad_medida     text,
  categoria         text,
  imagen            text,
  creado_en_almacen text not null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Código local: el mismo producto (mismo `producto_id`) puede tener un
-- código distinto en cada almacén, o ninguno todavía (si ese almacén nunca
-- lo movió). El correlativo de cada almacén (nextCodigo() en store.tsx)
-- escanea solo sus propias filas acá, así que cada almacén empieza en 1.
create table if not exists public.producto_codigos (
  almacen      text not null,
  producto_id  uuid not null references public.productos (id) on delete cascade,
  codigo       text not null,
  created_at   timestamptz not null default now(),
  primary key (almacen, codigo),
  unique (almacen, producto_id)
);

alter table public.movements
  add constraint movements_codigo_almacen_fkey
  foreign key (almacen, codigo) references public.producto_codigos (almacen, codigo)
  on update cascade;

-- Copia congelada de cada registro (número correlativo + lista de productos
-- tal como se registró / imprimió). No cambia aunque se edite o borre un movimiento.
create table if not exists public.comprobantes (
  id            text primary key,
  tipo          text not null check (tipo in ('Entrada', 'Salida')),
  numero        integer not null,
  periodo       text not null,             -- año; el correlativo reinicia cada año
  fecha         date not null,
  area          text not null,
  responsable   text not null,
  observaciones text,
  items         jsonb not null default '[]'::jsonb,
  movement_ids  text[] not null default '{}',
  almacen       text not null default 'las-flores',
  created_at    timestamptz not null default now(),
  unique (almacen, tipo, periodo, numero)
);

create index if not exists comprobantes_created_at_idx on public.comprobantes (created_at);
create index if not exists comprobantes_almacen_idx on public.comprobantes (almacen);

-- Traspaso de mercadería entre almacenes: el origen la crea (descuenta su
-- stock al toque) y queda "pendiente" hasta que el destino la recibe (recién
-- ahí suma su propio stock) o la rechaza. Es la única tabla donde una sesión
-- ve/toca legítimamente filas que no son 100% "suyas" — ver el trigger más
-- abajo, que además de RLS decide qué le permite cambiar a cada lado.
create table if not exists public.traspasos (
  id                    text primary key,
  numero                integer not null,
  periodo               text not null,
  almacen_origen        text not null,
  almacen_destino       text not null check (almacen_destino <> almacen_origen),
  estado                text not null default 'pendiente' check (estado in ('pendiente', 'recibido', 'cancelado')),
  fecha_envio           date not null,
  responsable_envio     text not null,
  motivo                text,
  items                 jsonb not null default '[]'::jsonb,
  movement_ids_salida   text[] not null default '{}',
  fecha_recepcion       date,
  responsable_recepcion text,
  items_recibidos       jsonb,
  items_rechazados      jsonb,
  movement_ids_entrada  text[] not null default '{}',
  motivo_cancelacion    text,
  created_at            timestamptz not null default now(),
  -- Global, no por almacen_origen: dos almacenes no pueden generar cada
  -- uno su propio "T-1" — ver migration-fase14.sql.
  unique (periodo, numero)
);

create index if not exists traspasos_origen_idx on public.traspasos (almacen_origen);
create index if not exists traspasos_destino_idx on public.traspasos (almacen_destino);

-- Contador atómico del número de traspaso, por período — ver
-- siguiente_numero_traspaso() más abajo.
create table if not exists public.traspaso_contadores (
  periodo text primary key,
  ultimo  integer not null default 0
);

alter table public.categories enable row level security;
alter table public.movements enable row level security;
alter table public.comprobantes enable row level security;
alter table public.traspasos enable row level security;
alter table public.productos enable row level security;
alter table public.producto_codigos enable row level security;

-- El almacén de la sesión viaja en el JWT (app_metadata), no en un mapeo
-- de correos hardcodeado dentro de cada política. Ver el paso 4 de
-- supabase/migration-fase6.sql para asignárselo a cada usuario.
create or replace function public.almacen_actual()
returns text
language sql
stable
as $$
  select nullif(
    (current_setting('request.jwt.claims', true)::jsonb -> 'app_metadata' ->> 'almacen'),
    ''
  );
$$;

-- La cuenta Administrador (rol en el JWT, no un almacén más) ve y escribe
-- CUALQUIER almacén — ver supabase/migration-fase9.sql para el detalle y
-- las advertencias de precedencia SQL al sumar este OR a cada política.
create or replace function public.es_admin()
returns boolean
language sql
stable
as $$
  select coalesce(
    (current_setting('request.jwt.claims', true)::jsonb -> 'app_metadata' ->> 'role') = 'admin',
    false
  );
$$;

-- Cada cuenta de acceso (CUENTAS en src/supabaseClient.ts) solo ve y escribe
-- las filas de SU "almacen" (o cualquiera, si es Administrador). Agregar una
-- cuenta nueva no toca estas políticas: solo hace falta el UPDATE del
-- paso 4 en migration-fase6.sql.
drop policy if exists "categories_public_access" on public.categories;
drop policy if exists "categories_por_almacen" on public.categories;
create policy "categories_por_almacen"
  on public.categories for all
  to authenticated
  using (almacen = public.almacen_actual() or public.es_admin())
  with check (almacen = public.almacen_actual() or public.es_admin());

drop policy if exists "movements_public_access" on public.movements;
drop policy if exists "movements_por_almacen" on public.movements;
create policy "movements_por_almacen"
  on public.movements for all
  to authenticated
  using (almacen = public.almacen_actual() or public.es_admin())
  with check (almacen = public.almacen_actual() or public.es_admin());

-- productos: a diferencia de las tablas de arriba, NO se filtra por
-- almacen_actual() — es el mismo catálogo para todas las cuentas
-- (cualquier almacenero o el admin lo ve y lo da de alta/edita). Sin
-- política de "for delete" a propósito: nadie borra un producto del
-- catálogo compartido desde la app.
drop policy if exists "productos_select" on public.productos;
create policy "productos_select"
  on public.productos for select
  to authenticated
  using (true);

drop policy if exists "productos_insert" on public.productos;
create policy "productos_insert"
  on public.productos for insert
  to authenticated
  with check (true);

drop policy if exists "productos_update" on public.productos;
create policy "productos_update"
  on public.productos for update
  to authenticated
  using (true)
  with check (true);

-- producto_codigos: el código local SÍ es por almacén — Umaru no puede
-- tocar la numeración de Las Flores ni viceversa (a diferencia de
-- productos, que es la identidad compartida y cualquiera la edita).
drop policy if exists "producto_codigos_select" on public.producto_codigos;
create policy "producto_codigos_select"
  on public.producto_codigos for select
  to authenticated
  using (true);

drop policy if exists "producto_codigos_insert" on public.producto_codigos;
create policy "producto_codigos_insert"
  on public.producto_codigos for insert
  to authenticated
  with check (almacen = public.almacen_actual() or public.es_admin());

drop policy if exists "producto_codigos_update" on public.producto_codigos;
create policy "producto_codigos_update"
  on public.producto_codigos for update
  to authenticated
  using (almacen = public.almacen_actual() or public.es_admin())
  with check (almacen = public.almacen_actual() or public.es_admin());

drop policy if exists "producto_codigos_delete" on public.producto_codigos;
create policy "producto_codigos_delete"
  on public.producto_codigos for delete
  to authenticated
  using (almacen = public.almacen_actual() or public.es_admin());

drop policy if exists "comprobantes_public_access" on public.comprobantes;
drop policy if exists "comprobantes_por_almacen" on public.comprobantes;
create policy "comprobantes_por_almacen"
  on public.comprobantes for all
  to authenticated
  using (almacen = public.almacen_actual() or public.es_admin())
  with check (almacen = public.almacen_actual() or public.es_admin());

-- traspasos: visible para origen Y destino (y para el admin); el trigger de
-- abajo decide qué puede cambiar cada lado (RLS sola no distingue a nivel
-- de columna).
drop policy if exists "traspasos_select" on public.traspasos;
create policy "traspasos_select"
  on public.traspasos for select
  to authenticated
  using (almacen_origen = public.almacen_actual() or almacen_destino = public.almacen_actual() or public.es_admin());

drop policy if exists "traspasos_insert" on public.traspasos;
create policy "traspasos_insert"
  on public.traspasos for insert
  to authenticated
  with check (
    (almacen_origen = public.almacen_actual() or public.es_admin())
    and estado = 'pendiente'
    and movement_ids_entrada = '{}'
    and items_recibidos is null
  );

drop policy if exists "traspasos_update" on public.traspasos;
create policy "traspasos_update"
  on public.traspasos for update
  to authenticated
  using (almacen_origen = public.almacen_actual() or almacen_destino = public.almacen_actual() or public.es_admin())
  with check (almacen_origen = public.almacen_actual() or almacen_destino = public.almacen_actual() or public.es_admin());

-- OJO: "is distinct from", nunca "<>" — varias columnas son NULL-eables y
-- "null <> algo" da NULL (no dispara el raise exception) en Postgres.
create or replace function public.traspasos_validar_transicion()
returns trigger
language plpgsql
as $$
declare
  yo text := public.almacen_actual();
  admin boolean := public.es_admin();
begin
  if not admin and yo is distinct from old.almacen_origen and yo is distinct from old.almacen_destino then
    raise exception 'No autorizado.';
  end if;
  if old.estado is distinct from 'pendiente' then
    raise exception 'Este traspaso ya no está pendiente.';
  end if;

  if new.estado = 'cancelado' then
    if new.items is distinct from old.items
       or new.numero is distinct from old.numero
       or new.almacen_origen is distinct from old.almacen_origen
       or new.almacen_destino is distinct from old.almacen_destino
       or new.movement_ids_salida is distinct from old.movement_ids_salida
       or new.movement_ids_entrada is distinct from old.movement_ids_entrada
       or new.items_recibidos is distinct from old.items_recibidos
       or new.items_rechazados is distinct from old.items_rechazados then
      raise exception 'Al cancelar solo se puede cambiar el estado y el motivo.';
    end if;
  elsif new.estado = 'recibido' then
    if not admin and yo is distinct from old.almacen_destino then
      raise exception 'Solo el almacén destino puede recibir.';
    end if;
    -- movement_ids_salida SÍ puede achicarse acá (recepción parcial): se le
    -- sacan los ids de las líneas rechazadas.
    if new.items is distinct from old.items
       or new.numero is distinct from old.numero
       or new.almacen_origen is distinct from old.almacen_origen
       or new.almacen_destino is distinct from old.almacen_destino
       or new.motivo_cancelacion is distinct from old.motivo_cancelacion then
      raise exception 'No se pueden modificar los datos de envío.';
    end if;
  else
    raise exception 'Transición de estado no permitida.';
  end if;

  return new;
end;
$$;

drop trigger if exists traspasos_before_update on public.traspasos;
create trigger traspasos_before_update
  before update on public.traspasos
  for each row
  execute function public.traspasos_validar_transicion();

-- El destino restituye el stock de origen de las líneas que rechaza. Se
-- llama desde dos momentos distintos: durante recibirTraspaso (recepción
-- parcial), con el traspaso TODAVÍA 'pendiente'; y desde cancelarTraspaso
-- cuando el destino rechaza todo, DESPUÉS de que esa misma función ya
-- marcó el traspaso 'cancelado' (a propósito: la bandera se actualiza
-- primero, ver el comentario en store.tsx) — por eso acepta los dos
-- estados, no solo 'pendiente'. RLS no deja tocar movements de otro
-- almacén (correcto) — esta función valida caso por caso antes de borrar.
create or replace function public.traspaso_restituir_rechazados(traspaso_id text, movement_ids text[])
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  t public.traspasos%rowtype;
begin
  select * into t from public.traspasos where id = traspaso_id;
  if t.id is null then
    raise exception 'No existe el traspaso.';
  end if;
  if t.almacen_destino is distinct from public.almacen_actual() and not public.es_admin() then
    raise exception 'No autorizado.';
  end if;
  if t.estado is distinct from 'pendiente' and t.estado is distinct from 'cancelado' then
    raise exception 'Este traspaso ya no se puede restituir.';
  end if;

  delete from public.movements
  where id = any(movement_ids)
    and id = any(t.movement_ids_salida)
    and almacen = t.almacen_origen;
end;
$$;

grant execute on function public.traspaso_restituir_rechazados(text, text[]) to authenticated;

-- Número de traspaso: correlativo GLOBAL (no por almacen_origen, ver el
-- unique de la tabla más arriba). Un "select max(numero)+1" desde el
-- cliente no sirve acá: no es atómico (dos envíos casi simultáneos podrían
-- calcular el mismo número) y, con RLS, cada cuenta solo ve los traspasos
-- donde participa — no puede calcular un máximo global por su cuenta. Esta
-- función corre con permisos propios y hace el incremento con un solo
-- UPSERT, que Postgres serializa fila por fila.
alter table public.traspaso_contadores enable row level security;

create or replace function public.siguiente_numero_traspaso(p_periodo text)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  n integer;
begin
  insert into public.traspaso_contadores (periodo, ultimo)
  values (p_periodo, 1)
  on conflict (periodo) do update set ultimo = public.traspaso_contadores.ultimo + 1
  returning ultimo into n;
  return n;
end;
$$;

grant execute on function public.siguiente_numero_traspaso(text) to authenticated;

insert into public.categories (name, almacen)
values
  ('Atención y servicio', 'las-flores'),
  ('Empaques y descartables', 'las-flores'),
  ('Mantenimiento', 'las-flores'),
  ('Tecnología y equipos', 'las-flores'),
  ('Seguridad', 'las-flores'),
  ('Atención y servicio', 'hotel-umaru'),
  ('Empaques y descartables', 'hotel-umaru'),
  ('Mantenimiento', 'hotel-umaru'),
  ('Tecnología y equipos', 'hotel-umaru'),
  ('Seguridad', 'hotel-umaru')
on conflict (almacen, name) do nothing;

-- Cuenta Administrador: correr esto DESPUÉS de crear el usuario en
-- Authentication → Users (corporacion2026@almacen.local, ver README) —
-- si el usuario no existe todavía, este UPDATE no hace nada.
update auth.users
set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role": "admin"}'::jsonb
where email = 'corporacion2026@almacen.local';

-- El Administrador cambia la contraseña de cualquier cuenta desde su panel
-- (auth.updateUser() solo cambia la de la sesión propia — esto escribe
-- directo el hash bcrypt en auth.users, con el mismo permiso con el que ya
-- se corren los UPDATE de app_metadata de más arriba).
create extension if not exists pgcrypto with schema extensions;

create or replace function public.admin_cambiar_password(objetivo_email text, nueva_password text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.es_admin() then
    raise exception 'Solo el administrador puede hacer esto.';
  end if;
  if nueva_password is null or length(nueva_password) < 6 then
    raise exception 'La contraseña debe tener al menos 6 caracteres.';
  end if;

  update auth.users
  set encrypted_password = extensions.crypt(nueva_password, extensions.gen_salt('bf')),
      updated_at = now()
  where email = objetivo_email;

  if not found then
    raise exception 'No existe una cuenta con ese correo.';
  end if;
end;
$$;

grant execute on function public.admin_cambiar_password(text, text) to authenticated;

-- ------------------------------------------------------------------
-- Almacenamiento de imágenes de producto (Supabase Storage)
-- ------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do nothing;

drop policy if exists "productos_public_read" on storage.objects;
create policy "productos_public_read"
  on storage.objects for select
  using (bucket_id = 'productos');

drop policy if exists "productos_auth_insert" on storage.objects;
create policy "productos_auth_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'productos');

drop policy if exists "productos_auth_update" on storage.objects;
create policy "productos_auth_update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'productos');

drop policy if exists "productos_auth_delete" on storage.objects;
create policy "productos_auth_delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'productos');
